[package]
name = "negentropy"
version = "0.1.0+taxus-baccata"
edition = "2021"

[dependencies]
aws-config = "1.5.4"
aws-sdk-s3 = "1.41.0"
futures = "0.3.30"
semver = { version = "1.0.23", features = ["serde"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
