
imports_granularity = "Module"
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
normalize_comments = true
hex_literal_case = "Lower"
format_strings = true
format_code_in_doc_comments = true
