[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = [
  "-C",
  "link-arg=-fuse-ld=/usr/bin/mold",
  "-Zcodegen-backend=cranelift",
  "-Z",
  "threads=8",
]

[target.aarch64-apple-darwin]
linker = "clang"
rustflags = ["-Z", "threads=8", "-C", "target-cpu=native"]
